import torch
from torch import Tensor
import torchmetrics
import typing
from typing import Union
import transformers
import os
import torch.nn.functional as F
from tqdm import tqdm
import math

try:
  from rouge_score import rouge_scorer
except ImportError:
  rouge_scorer = None

LOG2 = torch.log(torch.tensor(2.0))

class NLL(torchmetrics.aggregation.MeanMetric):
  pass

class BPD(NLL):
  def compute(self) -> Tensor:
    """Computes the bits per dimension.

    Returns:
      bpd
    """
    return self.mean_value / self.weight / LOG2

class Perplexity(NLL):
  def compute(self) -> Tensor:
    """Computes the Perplexity.

    Returns:
      Perplexity
    """
    return torch.exp(self.mean_value / self.weight)

class NFEs(torchmetrics.aggregation.MeanMetric):
  pass

class Metrics:
  def __init__(self, config=None) -> None:
    self.config=config
    metrics = torchmetrics.MetricCollection({
        'nll': NLL(), 'bpd': BPD(), 'ppl': Perplexity()})
    if hasattr(config, 'block_size'):
      self.block_size = config.block_size
    else:
      self.block_size = config.model.length
      
    self.nfes = NFEs()
    self.train_nlls = metrics.clone(prefix='train/')
    self.valid_nlls = metrics.clone(prefix='val/')
    self.gen_ppl = Perplexity()
    self.gen_rouge1 = torchmetrics.aggregation.MeanMetric()
    self.gen_rouge2 = torchmetrics.aggregation.MeanMetric()
    self.gen_rougeL = torchmetrics.aggregation.MeanMetric()
    self.gen_entropy = NLL()
    self.gen_ppls, self.gen_nfes, self.gen_entropies, self.gen_lengths \
      = [], [], [], []
    self.gen_rouge1s, self.gen_rouge2s, self.gen_rougeLs = [], [], []

    self.sampling_eps = config.training.sampling_eps
    if getattr(config.algo, 'clip_search_delta', None):
      self.clip_search_delta = config.algo.clip_search_delta
    self.valid_vars = {self.sampling_eps: []}
    if getattr(config.algo, 'var_min', None):
      self.valid_vars = self.init_valid_vars()
    self.eval_ppl_batch_size = \
     self.config.eval.perplexity_batch_size
    self.gen_ppl_eval_model_name_or_path = \
      config.eval.gen_ppl_eval_model_name_or_path
    self.tokenizer = transformers.AutoTokenizer.\
      from_pretrained(self.gen_ppl_eval_model_name_or_path)
    if self.tokenizer.pad_token is None:
      self.tokenizer.pad_token = self.tokenizer.eos_token
      self.tokenizer.pad_token_id = self.tokenizer.eos_token_id
    self.rouge_scorer = None
    if rouge_scorer is not None:
      self.rouge_scorer = rouge_scorer.RougeScorer(
        ['rouge1', 'rouge2', 'rougeL'],
        use_stemmer=True)

  def init_valid_vars(self):
    eps = self.sampling_eps
    if self.block_size > 1:
      eps = self.sampling_eps
      self.valid_vars = {(eps, 1): []}
      for width in self.config.algo.clip_search_widths:
        for i in torch.arange(0, 1 - width + self.clip_search_delta, self.clip_search_delta):
          min = torch.clamp(i, min=self.sampling_eps).item()
          max = torch.clamp(i + width, min=self.sampling_eps).item()
          self.valid_vars[(min, max)] = []
    else:
      eps = self.sampling_eps
      self.valid_vars = {
        (eps, 1): [],
        (1, 1): []}


  def to(self, *args, **kwargs):
    self.train_nlls = self.train_nlls.to(*args, **kwargs)
    self.valid_nlls = self.valid_nlls.to(*args, **kwargs)
    self.gen_ppl = self.gen_ppl.to(*args, **kwargs)
    self.gen_rouge1 = self.gen_rouge1.to(*args, **kwargs)
    self.gen_rouge2 = self.gen_rouge2.to(*args, **kwargs)
    self.gen_rougeL = self.gen_rougeL.to(*args, **kwargs)
    self.nfes = self.nfes.to(*args, **kwargs)
    self.gen_entropy = self.gen_entropy.to(*args, **kwargs)

  def reset(self):
    self.gen_ppls, self.gen_nfes, self.gen_entropies, self.gen_lengths \
      = [], [], [], []
    self.gen_rouge1s, self.gen_rouge2s, self.gen_rougeLs = [], [], []
    self.train_nlls.reset()
    self.valid_nlls.reset()
    self.gen_ppl.reset()
    self.gen_rouge1.reset()
    self.gen_rouge2.reset()
    self.gen_rougeL.reset()
    self.gen_entropy.reset()
    self.nfes.reset()
    if getattr(self.config.algo, 'var_min', None):
      self.init_valid_vars()

  @torch.no_grad()
  def _eval_retokenize(self, text_samples, max_length,
                       device):
    """Retokenizes samples for the eval model.
    
    Args:
        text_samples: List of sentences generated by the model.
    Returns:
        samples: Samples re-tokenized for the eval model
        attn_mask: Attention mask for the eval model
        eval_context_size: Size of the context for the eval model
    """
    if 'llama2' in self.gen_ppl_eval_model_name_or_path:
      tokenizer_kwargs = {
        'text_samples': text_samples,
        'return_tensors': 'pt',
        'return_token_type_ids': False,
        'return_attention_mask': True,
        'truncation': True,
        'padding': True,
        'max_length': max_length,
      }
      eval_context_size = 4096
    else:
      tokenizer_kwargs = {
        'return_tensors': 'pt',
        'return_token_type_ids': False,
        'return_attention_mask': True,
        'truncation': True,
        'padding': True,
        'max_length': max_length,
      }
      eval_context_size = 1024
    samples = self.tokenizer(text_samples,
                             **tokenizer_kwargs)
    attn_mask = samples['attention_mask']
    samples = samples['input_ids']
    if 'llama2' not in self.gen_ppl_eval_model_name_or_path:
      attn_mask = attn_mask.to(device)
      samples = samples.to(device)      
    return samples, attn_mask, eval_context_size

  @staticmethod
  def _rouge_tokens(text: str) -> typing.List[str]:
    text = '' if text is None else str(text)
    text = text.lower().replace('\n', ' ')
    text = ' '.join(text.split())
    if not text:
      return []
    return text.split(' ')

  @staticmethod
  def _ngram_counts(tokens: typing.List[str], n: int):
    counts = {}
    for i in range(len(tokens) - n + 1):
      ngram = tuple(tokens[i:i + n])
      counts[ngram] = counts.get(ngram, 0) + 1
    return counts

  @staticmethod
  def _f1_from_overlap(overlap: int, pred_total: int, ref_total: int) -> float:
    if overlap <= 0 or pred_total <= 0 or ref_total <= 0:
      return 0.0
    precision = overlap / pred_total
    recall = overlap / ref_total
    if precision + recall == 0:
      return 0.0
    return 2 * precision * recall / (precision + recall)

  def _rouge_n_f1(
    self,
    pred_tokens: typing.List[str],
    ref_tokens: typing.List[str],
    n: int,
  ) -> float:
    if len(pred_tokens) < n or len(ref_tokens) < n:
      return 0.0

    pred_counts = self._ngram_counts(pred_tokens, n)
    ref_counts = self._ngram_counts(ref_tokens, n)
    overlap = 0
    for ngram, pred_count in pred_counts.items():
      overlap += min(pred_count, ref_counts.get(ngram, 0))
    return self._f1_from_overlap(
      overlap=overlap,
      pred_total=sum(pred_counts.values()),
      ref_total=sum(ref_counts.values()))

  @staticmethod
  def _lcs_length(
    pred_tokens: typing.List[str],
    ref_tokens: typing.List[str],
  ) -> int:
    if not pred_tokens or not ref_tokens:
      return 0

    dp = [0] * (len(ref_tokens) + 1)
    for pred_token in pred_tokens:
      prev_diag = 0
      for j, ref_token in enumerate(ref_tokens, start=1):
        prev_up = dp[j]
        if pred_token == ref_token:
          dp[j] = prev_diag + 1
        else:
          dp[j] = max(dp[j], dp[j - 1])
        prev_diag = prev_up
    return dp[-1]

  def _rouge_l_f1(
    self,
    pred_tokens: typing.List[str],
    ref_tokens: typing.List[str],
  ) -> float:
    lcs = self._lcs_length(pred_tokens, ref_tokens)
    return self._f1_from_overlap(
      overlap=lcs,
      pred_total=len(pred_tokens),
      ref_total=len(ref_tokens))

  def record_rouge_scores(
    self,
    predictions: typing.List[str],
    references: typing.List[str],
  ) -> None:
    if len(predictions) != len(references):
      raise ValueError(
        f'ROUGE expects equal number of predictions and references, '
        f'got {len(predictions)} predictions vs {len(references)} references.')

    self.gen_rouge1.reset()
    self.gen_rouge2.reset()
    self.gen_rougeL.reset()
    self.gen_rouge1s, self.gen_rouge2s, self.gen_rougeLs = [], [], []

    for pred, ref in zip(predictions, references):
      if self.rouge_scorer is not None:
        rouge_scores = self.rouge_scorer.score(ref or '', pred or '')
        rouge1 = rouge_scores['rouge1'].fmeasure
        rouge2 = rouge_scores['rouge2'].fmeasure
        rougeL = rouge_scores['rougeL'].fmeasure
      else:
        pred_tokens = self._rouge_tokens(pred)
        ref_tokens = self._rouge_tokens(ref)

        rouge1 = self._rouge_n_f1(pred_tokens, ref_tokens, n=1)
        rouge2 = self._rouge_n_f1(pred_tokens, ref_tokens, n=2)
        rougeL = self._rouge_l_f1(pred_tokens, ref_tokens)

      self.gen_rouge1s.append(rouge1)
      self.gen_rouge2s.append(rouge2)
      self.gen_rougeLs.append(rougeL)

      self.gen_rouge1.update(rouge1)
      self.gen_rouge2.update(rouge2)
      self.gen_rougeL.update(rougeL)
    
  @torch.no_grad()
  def record_conditional_perplexity(
      self,
      prefixes,
      answers,
      max_length=2048,
      batch_size=None,
      device='cuda',
  ):
      """
      计算 conditional PPL：只对 answer 部分计 loss，prefix 只作为上下文。
      用的是 eval causal LM（gen_ppl_eval_model_name_or_path），不是 diffusion model 自己的 nll。
      """
      os.environ['TOKENIZERS_PARALLELISM'] = 'false'
      eval_model = transformers.AutoModelForCausalLM.from_pretrained(
          self.gen_ppl_eval_model_name_or_path
      ).eval().to(device)

      tok = self.tokenizer
      if batch_size is None:
          batch_size = min(self.eval_ppl_batch_size, len(prefixes))

      # reset
      self.gen_ppl.reset()
      self.gen_ppls = []

      for st in range(0, len(prefixes), batch_size):
          p_batch = prefixes[st:st+batch_size]
          a_batch = answers[st:st+batch_size]

          # 分开 tokenize，避免 prefix/answer 边界被重新分词搞乱
          p = tok(p_batch, add_special_tokens=False, padding=True, truncation=True,
                  max_length=max_length, return_tensors='pt')
          a = tok(a_batch, add_special_tokens=False, padding=True, truncation=True,
                  max_length=max_length, return_tensors='pt')

          p_ids = p['input_ids'].to(device)
          p_mask = p['attention_mask'].to(device)
          a_ids = a['input_ids'].to(device)
          a_mask = a['attention_mask'].to(device)

          # 拼接 prefix + answer
          # 对每个样本按实际长度拼接，再 pad 成 batch
          seqs = []
          ans_loss_masks = []
          for i in range(p_ids.size(0)):
              p_len = int(p_mask[i].sum().item())
              a_len = int(a_mask[i].sum().item())

              seq = torch.cat([p_ids[i, :p_len], a_ids[i, :a_len]], dim=0)

              # loss mask：只在 answer token 对应的位置计 loss（注意 next-token prediction 要 shift）
              # 我们用 labels = seq[1:], logits = seq[:-1]
              # 那么要计算 answer 的 token y_t，应该 mask 覆盖 seq 的 answer 区间（对应 labels 的位置）
              loss_mask = torch.zeros_like(seq, dtype=torch.float32)
              # answer 在 seq 中的区间是 [p_len, p_len+a_len)
              loss_mask[p_len:p_len+a_len] = 1.0

              seqs.append(seq)
              ans_loss_masks.append(loss_mask)

          # pad
          pad_id = tok.pad_token_id
          maxL = max(s.numel() for s in seqs)
          input_ids = torch.full((len(seqs), maxL), pad_id, device=device, dtype=torch.long)
          attn_mask = torch.zeros((len(seqs), maxL), device=device, dtype=torch.long)
          loss_mask = torch.zeros((len(seqs), maxL), device=device, dtype=torch.float32)

          for i, (s, lm) in enumerate(zip(seqs, ans_loss_masks)):
              L = s.numel()
              input_ids[i, :L] = s
              attn_mask[i, :L] = 1
              loss_mask[i, :L] = lm

          # forward + token NLL
          logits = eval_model(input_ids, attention_mask=attn_mask).logits  # [B, L, V]
          # next-token
          shift_logits = logits[:, :-1, :].transpose(-1, -2)               # [B, V, L-1]
          shift_labels = input_ids[:, 1:]                                  # [B, L-1]
          shift_loss_mask = loss_mask[:, 1:]                               # [B, L-1] 对齐 labels

          nll = F.cross_entropy(shift_logits, shift_labels, reduction='none')  # [B, L-1]
          denom = shift_loss_mask.sum(dim=-1).clamp(min=1.0)
          mean_nll = (nll * shift_loss_mask).sum(dim=-1) / denom              # [B]
          ppl = torch.exp(mean_nll)

          # 记录到 gen_ppl（保持你原来 compute() 的接口）
          self.gen_ppls.extend(ppl.detach().cpu().tolist())
          self.gen_ppl.update(nll, shift_loss_mask)


  @torch.no_grad()
  def record_generative_perplexity(
    self,
    text_samples: typing.List[str],
    max_length: int,
    batch_size: Union[int, None] = None,
    retokenize: bool = True,
    stride=512,
    device='cuda') -> None:
    os.environ['TOKENIZERS_PARALLELISM'] = 'false'
    eval_model = transformers.AutoModelForCausalLM.from_pretrained(
      self.gen_ppl_eval_model_name_or_path).eval()
    if 'llama2' not in self.gen_ppl_eval_model_name_or_path:
      eval_model = eval_model.to(device)
    # Re-tokenize using eval model's tokenizer
    if retokenize:
      (samples, attn_mask,
       eval_context_size) = self._eval_retokenize(
         text_samples, max_length=max_length, device=device)
    else:
      samples = text_samples
      attn_mask = torch.ones(samples.shape).to(device)
      eval_context_size = samples.shape[-1]
    if batch_size is None:
      batch_size = min(self.eval_ppl_batch_size,
                      samples.shape[0])

    num_batches = samples.shape[0] // batch_size
    for i in range(num_batches):
      samples_batch = samples[i * batch_size: (i + 1) * batch_size]
      attn_mask_batch = attn_mask[i * batch_size: (i + 1) * batch_size]

      nlls_accum = torch.zeros_like(samples_batch, dtype=torch.float32)
      valid_tokens_accum = torch.zeros_like(samples_batch, dtype=torch.float32)

      num_strides = math.ceil((samples_batch.shape[-1] - eval_context_size + stride) / stride)
      num_strides = max(num_strides, 1)

      # Computes Gen. PPL in a sliding window for sequences longer than eval_context_size
      for i in tqdm(range(num_strides), desc='Sliding Window Gen PPL'):
        if i == 0:
          # for the first stride, use the entire eval_context_size
          start = 0
          end = min(eval_context_size, samples_batch.shape[-1])
        else:
          # then, move the window by stride
          start = i * stride
          end = min(start + eval_context_size, samples_batch.shape[-1])
        sample_chunk = samples_batch[..., start:end]
        attn_mask_chunk = attn_mask_batch[..., start:end]

        logits = eval_model(sample_chunk, attention_mask=attn_mask_chunk)[0]
        logits = logits.transpose(-1, -2)
        
        nlls = F.cross_entropy(logits[..., :-1], sample_chunk[..., 1:], reduction='none')
        valid_tokens = (sample_chunk[..., 1:] != self.tokenizer.eos_token_id).to(torch.float)
        
        if i == 0:
          # for the first stride, update the nlls of the entire eval_context_size
          nlls_accum[..., start + 1:end] += nlls
          valid_tokens_accum[..., start + 1:end] += valid_tokens
        else:
          # only update the nlls of the last stride
          update_start = (start+eval_context_size-stride)
          update_window = end - update_start
          nlls_accum[...,update_start:end] += nlls[..., -update_window:]
          valid_tokens_accum[..., update_start:end] += valid_tokens[..., -update_window:]
          
      # gen ppl
      avg_nll = (nlls_accum * valid_tokens_accum).sum() / valid_tokens_accum.sum()
      self.gen_ppls.append(avg_nll.exp().detach().cpu().item())
      self.gen_ppl.update(nlls_accum, valid_tokens_accum)

      # entropy
      entropy_full = 0
      for i in range(samples_batch.shape[0]):
        _, counts = torch.unique(samples_batch[i], return_counts=True, sorted=False)
        entropy = torch.special.entr(counts.float() / counts.sum()).sum()
        entropy_full += entropy
      self.gen_entropies.append(entropy_full.detach().cpu().item())
      self.gen_entropy.update(entropy_full, samples_batch.shape[0])

      # record sample length
      self.gen_lengths.append(valid_tokens_accum.sum().detach().cpu().item())
